### ISSUE TITLE
match

### ISSUE THREAD

**Issue by MurkBRA** [Tackyou/orlygift-cleaner#1]
The match simple work only on main page
if you change to something like this:
`// @include /^https?://www\.orlygift\.com.*/`
work fine on all pages of site.

I did some css changes on my personal script to avoid some popup, ads and restore scroll.
".col-md-offset-2.col-md-8 > br, .ng-scope > br, .sweet-overlay, .blocked-overlay, .alert-danger, #commander-cool-banner, #orlygift_tutorial, .sweet-alert.showSweetAlert.visible, .ad-container, #exit-intent-guest, #exit-intent-user, .modal-backdrop.fade.in {visibility: hidden !important; display: none !important;}",
".stop-scrolling {overflow: inherit !important; height: inherit !important;}",
".modal-open {overflow: auto !important;}",

And thank you, very nice script that you did.

**Comment by Tackyou** [comment]
Hey,

thanks for your suggestions.

I don't use Orlygift anymore so I'm no more checking if the script works and stopped doing updates.

If you want to fork it add your changes and make a merge request I would be happy to accept it tho.
